#! /bin/sh

OBS_PROJECT=isv:ownCloud:community
OBS_MIRRORS=http://download.opensuse.org/repositories

QUICK=true		# true: skip update and disk sanitation. false: do everything

if [ "$1" == "-h" ]; then
  echo "Usage: $0 [OBS_PROJECT]"
  echo "default OBS_PROJECT is '$OBS_PROJECT'"
  exit 1
fi
test -n "$1" && OBS_PROJECT=$1

cd $(dirname $0)

buildPlatform=xUbuntu_14.04	# matches an OBS target.
OBS_REPO=$OBS_MIRRORS/$(echo $OBS_PROJECT | sed -e 's@:@:/@g')/$buildPlatform

ocVersion=$(curl -s -L $OBS_REPO/Packages | grep -a1 'Package: owncloud$' | grep Version: | head -n 1 | sed -e 's/Version: /owncloud-/')
# ocVersion=ownCloud-8.1.0-6
vmBoxName=ubuntu/trusty64
vmBoxUrl=https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box

cat > Vagrantfile << EOF
# CAUTION: Do not edit. Autogenerated contents.
# This Vagrantfile is created by $0 "$@"
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "$vmBoxName"

  # avoids 'stdin: is not a tty' error.
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile LC_ALL=C exec bash'" 

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "$vmBoxUrl"

  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.provider :virtualbox do |vb|
      vb.name = "$buildPlatform+$ocVersion"
  end
	config.vm.provision "shell", inline: <<-SCRIPT
		set -x
		sudo useradd owncloud -m -p owncloud
		echo "admin\nadmin" | sudo passwd
		wget $OBS_REPO/Release.key -O Release.key
		sudo apt-key add - < Release.key 
		rm Release.key
		ls -la
		sudo sh -c "echo 'deb $OBS_REPO /' >> /etc/apt/sources.list.d/owncloud.list"
		sudo apt-get update -y
		$QUICK || sudo apt-get upgrade -y
		# sudo apt-get install -y language-pack-de 	# if LC_ALL=C does not help

		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin'
		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin'
		sudo apt-get install -y owncloud
		cd /var/www/owncloud/apps
		curl -s localhost/owncloud/ | grep login

		sudo mkdir -p /var/scripts
		sudp cp /vagrant/*.sh /var/scripts
		sudo a2enmod ssl headers
		sudo a2dissite default-ssl

		# “zero out” the drive...
		$QUICK || sudo dd if=/dev/zero of=/EMPTY bs=1M
		$QUICK || sudo rm -f /EMPTY
	SCRIPT
end
EOF


vagrant up
exit 0
vagrant halt
imageName=$buildPlatform+$ocVersion
VBoxImagePath=$(VBoxManage list hdds | grep '/$imageName/')
#-->Location:       /home/$USER/VirtualBox VMs/ownCloud-8.1.1+xUbuntu_14.04/box-disk1.vmdk
VBoxImagePath=${VBoxImagePath#*/}
VBoxImageName=${VBoxImagePath##*/}
VBoxImagePath=/$VBoxImagePath
cp "$VBoxImagePath" $imageName.vmdk
zip $imageName.vmdk.zip $imageName.vmdk
rm $imageName.vmdk

if [ "$VBoxImagePath" != "" ]
then vagrant destroy -f
fi
